# Simulation constants

# === ORGANISM PARAMETERS ===
STARTING_ENERGY = 100.0
ENERGY_DECAY_RATE = 0.1
REPRODUCTION_ENERGY_THRESHOLD = 150.0
REPRODUCTION_ENERGY_COST = 50.0
REPRODUCTION_COOLDOWN_FRAMES = 300  # 5 seconds at 60 FPS

# === GENE RANGES ===
GENE_COLOR_MIN = 0
GENE_COLOR_MAX = 255
GENE_SPEED_MIN = 0.5
GENE_SPEED_MAX = 2.0
GENE_SIZE_MIN = 1
GENE_SIZE_MAX = 8
GENE_PHOTO_MIN = 0.0
GENE_PHOTO_MAX = 1.0

# === MUTATION RATES ===
MUTATION_RANGE_COLOR = 10  # +/- for RGB values
MUTATION_RANGE_SPEED = 0.1
MUTATION_RANGE_SIZE = 1
MUTATION_RANGE_PHOTO = 0.01

# === PHENOTYPE EXPRESSION ===
SPEED_MULTIPLIER = 5  # gene * multiplier = actual speed
SIZE_BASE = 3  # minimum radius
SIZE_MULTIPLIER = 10  # gene * multiplier + base = radius
PHOTOSYNTHESIS_THRESHOLD = 0.3  # minimum gene value to photosynthesize
PHOTOSYNTHESIS_EFFICIENCY = 0.15  # energy gain multiplier
GREEN_BOOST_PHOTO = 127.5  # green channel boost for photosynthetic

# === ENVIRONMENT ===
DEFAULT_SUNLIGHT_LEVEL = 0.8
BACKGROUND_COLOR = (20, 20, 40)
FOOD_SPAWN_INTERVAL = 600  # frames
FOOD_SPAWN_AMOUNT = 5


# === SIMULATION ===
FPS = 60
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FONT_SIZE = 32
FONT_COLOR = (255, 255, 255)  # White 